general.import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "alacritty"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.9
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\\u0000-\\u001F\\u007F-\\u009F<>\"\\s{-}\\^⟨⟩`]+"
mouse = { enabled = true, mods = "Command" }
binding = { key = "U", mods = "Control|Shift" }

